StorPedramBackend/Areas/Admin/Controllers/BannersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CorService.ExtinsionMethod;
using CorService.Security;
using CorService.Services.IService;
using CorService.Services.SliderService;
using DataLayer.Entites;
using Microsoft.AspNetCore.Mvc;
using static CorService.ViewModels.Slider.SliderViewModel;

namespace StorPedramBackend.Areas.Admin.Controllers
{
    [Area("Admin")]
    [AutoValidateAntiforgeryToken]
    public class BannersController : Controller
    {
        ISlider _Slider;
        IBannerService _BannerService;
        public BannersController(ISlider Slider, IBannerService BannerService)
        {
            _Slider = Slider;
            _BannerService = BannerService;
        }
        #region Slider
        public IActionResult SliderList()
        {
            return View(_Slider.GetSlierForAdmin());
        }
        public IActionResult DeleteSlider(int id)
        {
            Slider slider = _Slider.FindSliderById(id);
            if (slider == null)
            {
                TempData["res"] = "faild";
                return RedirectToAction("SliderList");
            }
            bool res = _Slider.DeleteSlider(slider);
            if (res)
            {
                slider.ImgName.DeleteImage("wwwroot/img/slider/");
                slider.ImgName.DeleteImage("wwwroot/img/slider/mobile-slider/");
            }
            TempData["res"] = res ? "success" : "faild";

            return RedirectToAction("SliderList");
        }
        public IActionResult CreateSlider()
        {
            return View();
        }
        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult CreateSlider(CreateSliderViewModel slid)
        {
            if (!ModelState.IsValid)
            {
                return View(slid);
            }
            string filename = "";
            if (ImgeSecurity.ImageValitor(slid.DesktopImg))
            {
                filename = slid.DesktopImg.SaveImage("", "wwwroot/img/slider");
            }
            else
            {
                ModelState.AddModelError("DesktopImg", "لطفا یک فایل عکس قرار بدید");
            }
            if (ImgeSecurity.ImageValitor(slid.MobileImg))
            {
                slid.MobileImg.SaveImage(filename, "wwwroot/img/slider/mobile-slider");
            }
            else
            {
                ModelState.AddModelError("MobileImg", "لطفا یک فایل عکس قرار بدید");
            }
            Slider sl = new Slider
            {
                ImgName = filename,
                Descrption = slid.Descrption,
                Link = slid.Link,
                sort = slid.sort,
            };
            bool res = _Slider.AddSlider(sl);
            TempData["res"] = res ? "success" : "faild";
            return RedirectToAction("SliderList");
        }
        public IActionResult EditSlider(int id)
        {
            Slider slid = _Slider.FindSliderById(id);
            if (slid == null)
            {
                TempData["res"] = "faild";
            }
            EditSliderViewModel slvm = new EditSliderViewModel
            {
                sliderid = slid.SliderId,
                CurrentImgName = slid.ImgName,
                Descrption = slid.Descrption,
                Link = slid.Link,
                sort = slid.sort
            };
            return View(slvm);
        }
        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult EditSlider(EditSliderViewModel edit)
        {
            if (!ModelState.IsValid)
            {
                return View(edit);
            }

            string filname = TempData["imgename"].ToString();
            if (edit.DesktopImg != null)
            {
                if (ImgeSecurity.ImageValitor(edit.DesktopImg))
                {
                    filname.DeleteImage("wwwroot/img/slider/");

                    edit.DesktopImg.SaveImage(filname, "wwwroot/img/slider/");

                }
                else
                {
                    ModelState.AddModelError("DesktopImg", "لطفا یک فایل عکس قرار بدید");
                }
                if (ImgeSecurity.ImageValitor(edit.MobileImg))
                {
                    edit.MobileImg.SaveImage(filname, "wwwroot/img/slider/mobile-slider");
                }
                else
                {
                    ModelState.AddModelError("MobileImg", "لطفا یک فایل عکس قرار بدید");
                }
                Slider sl = new Slider
                {
                    SliderId = int.Parse(TempData["sliderid"].ToString()),
                    sort = edit.sort,
                    Descrption = edit.Descrption,
                    ImgName = filname,
                    Link = edit.Link,
                };
                bool res = _Slider.updateSlider(sl);
                TempData["res"] = res ? "success" : "faild";
            }
            return RedirectToAction("SliderList");
        }
        #endregion
        #region Banner
        public IActionResult BannerList()
        {
            return View(_BannerService.GetBannerForAdmin());
        }
        public IActionResult ChangeActive(int id)
        {
            ViewData["Title"]= _BannerService.ChangeActiveBanner(id)?"succsse":"faild";
            return RedirectToAction("BannerList");
        }
        #endregion
    }
}

StorPedramBackend/Areas/Admin/Controllers/orderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CorService.Services.IService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace StorPedramBackend.Areas.Admin.Controllers
{
    public class orderController : Controller
    {
        private ICartService _cartService;
        public orderController(ICartService cartService)
        {
            _cartService = cartService;
        }
        [Area("Admin")]
        [Authorize]
        public IActionResult orderList()
        {
            return View(_cartService.getAllorderforAdmin());
        }
    }
}

StorPedramBackend/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>داشبرد | کنترل پنل مدیریت</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="/admin/dist/css/bootstrap-theme.css">
    <!-- Bootstrap rtl -->
    <link rel="stylesheet" href="/admin/dist/css/rtl.css">
    <!-- persian Date Picker -->
    <link rel="stylesheet" href="/admin/dist/css/persian-datepicker-0.4.5.min">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/admin/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="/admin/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/admin/dist/css/AdminLTE.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/admin/dist/css/skins/_all-skins.min.css">
    <!-- Morris chart -->
    <!-- jvectormap -->
    <link rel="stylesheet" href="/admin/bower_components/jvectormap/jquery-jvectormap.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="/admin/bower_components/bootstrap-daterangepicker/daterangepicker.css">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="/admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
    <link href="~/Admin/plugins/iCheck/flat/blue.css" rel="stylesheet" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <script src="/admin/bower_components/jquery/dist/jquery.min.js"></script>
    @RenderSection("style", false)
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

        <header class="main-header">
            <!-- Logo -->
            <a href="index2.html" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini">پنل</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>کنترل پنل مدیریت</b></span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>


                <!-- Delete This after download -->
                <!-- End Delete-->


                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- Messages: style can be found in dropdown.less-->
                        <!-- Notifications: style can be found in dropdown.less -->
                        <!-- Tasks: style can be found in dropdown.less -->
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <span class="hidden-xs">پدرام کامرانی</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">

                                    <p>
                                        پدرام کامرانی
                                        <small>مدیریت کل سایت</small>
                                    </p>
                                </li>
                                <!-- Menu Body -->
                                <li class="user-body">
                                    <div class="row">
                                        <div class="col-xs-4 text-center">
                                            <a href="#">صفحه من</a>
                                        </div>
                                        <div class="col-xs-4 text-center">
                                            <a href="#">فروش</a>
                                        </div>
                                        <div class="col-xs-4 text-center">
                                            <a href="#">دوستان</a>
                                        </div>
                                    </div>
                                    <!-- /.row -->
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-right">
                                        <a href="#" class="btn btn-default btn-flat">پروفایل</a>
                                    </div>
                                    <div class="pull-left">
                                        <a href="#" class="btn btn-default btn-flat">خروج</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <!-- Control Sidebar Toggle Button -->
                        <li>
                            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- right side column. contains the logo and sidebar -->
        @await Html.PartialAsync("_RightMenu")

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @RenderBody()
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer text-left">
        </footer>

        <!-- Control Sidebar -->
        <!-- /.control-sidebar -->
        <!-- Add the sidebar's background. This div must be placed
        immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 3 -->
    <!-- jQuery UI 1.11.4 -->
    <script src="/admin/bower_components/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>$.widget.bridge('uibutton', $.ui.button);</script>
    <!-- Bootstrap 3.3.7 -->
    <script src="/admin/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- Morris.js charts -->
    <script src="/admin/bower_components/raphael/raphael.min.js"></script>
    <!-- Sparkline -->
    <script src="/admin/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
    <!-- jvectormap -->
    <script src="/admin/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="/admin/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="/admin/bower_components/jquery-knob/dist/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="/admin/bower_components/moment/min/moment.min.js"></script>
    <script src="/admin/bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
    <!-- datepicker -->
    <script src="bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="/admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
    <!-- Slimscroll -->
    <script src="/admin/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="bower_components/fastclick/lib/fastclick.js"></script>
    <script src="~/Admin/plugins/iCheck/icheck.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/admin/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="/admin/dist/js/pages/dashboard.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/admin/dist/js/demo.js"></script>
    @RenderSection("script", false)
</body>
</html>

StorPedramBackend/Areas/Admin/Views/Shared/_RightMenu.cshtml
@{
    string Controller = ViewContext.RouteData.Values["Controller"].ToString();
    string Action = ViewContext.RouteData.Values["Action"].ToString();
    
}
<aside class="main-sidebar">
     sidebar: style can be found in sidebar.less 
    <section class="sidebar">
         Sidebar user panel 
        <div class="user-panel">
            <div class="pull-right image">
                <img src="/img/back_edit.png" class="img-circle" alt="User Image">
            </div>
            <div class="pull-right info">
                <p>پدرام کامرانی</p>
                <a href="#"><i class="fa fa-circle text-success"></i> آنلاین</a>
            </div>
        </div>
         search form 
         /.search form 
         sidebar menu: : style can be found in sidebar.less 
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">منو</li>
            <li class="treeview @(Controller == "Banner" ? "active" :"")">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>بنر</span>
                    <span class="pull-left-container">
                        <i class="fa fa-angle-right pull-left"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="@(Action.Contains("Slider") ? "active":"") "><a asp-area="Admin" asp-controller="Banners" asp-action="SliderList"><i class="fa fa-circle-o"></i>  اسلایدر اصلی</a></li>
                    <li class="@(Action.Contains("Banner") ? "active":"") "><a asp-controller="Banners" asp-action="BannerList"><i class="fa fa-circle-o"></i> بنرها</a></li>

                </ul>
            </li>
            <li class=" treeview @(Controller == "Catalog" || Controller == "FileManager" ? "active" :"")">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>کاتالوگ</span>
                    <span class="pull-left-container">
                        <i class="fa fa-angle-right pull-left"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="@(Action.Contains("Product") ? "active":"")"><a asp-controller="Catalog" asp-action="ProductList"><i class="fa fa-circle-o"></i>  محصولات</a></li>
                    <li class="@(Action.Contains("Category") ? "active":"")"><a asp-controller="Catalog" asp-action="CategoryList"><i class="fa fa-circle-o"></i>  دسته بندی ها</a></li>
                    <li class="@(Action.Contains("Brand") ? "active":"")"><a asp-controller="Catalog" asp-action="BrandList"><i class="fa fa-circle-o"></i>  برندها</a></li>
                    <li class="@(Action.Contains("Rating") ? "active":"")"><a asp-controller="Catalog" asp-action="RatingAttributeList"><i class="fa fa-circle-o"></i>  ویژگی ها</a></li>
                    <li class="@(Action.Contains("FileManager") ? "active":"")"><a asp-controller="FileManager" asp-action="MainFileManager"><i class="fa fa-circle-o"></i>  مدیریت فایل ها </a></li>
                    <li class="treeview  @(Action.Contains("Property") ? "menu-open active":"")">
                        <a href="#">
                            <i class="fa fa-circle-o"></i> خصوصیات
                            <span class="pull-left-container">
                                <i class="fa fa-angle-right pull-left"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu" style="display: @(Action.Contains("Property") ? "block":"")">
                            <li class="@(Action.Contains("PropertyGroup") ? "active":"")"><a asp-controller="Catalog" asp-action="ProprtyGroupList" asp-route-id="1"><i class="fa fa-circle-o"></i>  گروه خصوصیات</a></li>
                            <li class="@(Action.Contains("PropertyName") ? "active":"")"><a asp-controller="Catalog" asp-action="PropertyNameList"><i class="fa fa-circle-o"></i>  نام خصوصیات</a></li>
                            <li class="@(Action.Contains("PropertyValue") ? "active":"")"><a asp-controller="Catalog" asp-action="PropertyValueList"><i class="fa fa-circle-o"></i>  مقدار خصوصیات</a></li>

                        </ul>
                    </li>
                </ul>
            </li>
            <li class=" treeview @(Controller == "Modules" ? "active" :"")">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>ماژول</span>
                    <span class="pull-left-container">
                        <i class="fa fa-angle-right pull-left"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="@(Action.Contains("Menu") ? "active":"")"><a asp-controller="Modules" asp-action="MenuList"><i class="fa fa-circle-o"></i>  منو اصلی  </a></li>

                </ul>
            </li>

            <li class=" treeview @(Controller == "User" ? "active" :"")">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>کاربران</span>
                    <span class="pull-left-container">
                        <i class="fa fa-angle-right pull-left"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="@(Action.Contains("Role") ? "active":"")"><a asp-controller="User" asp-action="RoleList"><i class="fa fa-circle-o"></i> نقش ها </a></li>
                    <li class="@(Action.Contains("Factor") ? "active":"")"><a asp-controller="order" asp-action="orderList"><i class="fa fa-circle-o"></i> فاکتورها  </a></li>

                </ul>
            </li>


        </ul>
    </section>
     /.sidebar 
</aside>